version: "3.0.0"
services:
  oraclejdk-8:
    build: oraclejdk-8
    container_name: oraclejdk-8
    command: "true"
    restart: "no"

  teamcity:
    build: teamcity
    restart: always
    ports:
    - "8111:8111"
    volumes:
    - ./teamcity/storage:/root/BuildServer

  teamcityagent:
    build: teamcity-agent
    restart: always
    links:
    - teamcity
    - mysql

  mysql:
    image: armbuild/orchardup-mysql
    restart: always
    environment:
      MYSQL_DATABASE: aufhaxedev_testing
      MYSQL_ROOT_PASSWORD: root
